"""Libreria generica di immagini (riusabili in tutti i reel e dal bot automatico).
Ogni voce: id -> (tema, scena). Il personaggio e lo stile vengono aggiunti dal generatore."""
import json
import os

T = {}

T["emotions"] = [
    "The wolf jumps for joy with both fists in the air, confetti falling, big smile.",
    "The wolf sits on a bench looking sad, rain falling, shoulders down.",
    "The wolf is furious, red face with steam coming out of his ears, fists clenched.",
    "The wolf with jaw dropped in total shock, eyes wide open, hands on cheeks.",
    "The wolf thinking deeply with a paw on his chin, thought bubbles with question marks floating.",
    "The wolf confused, scratching his head, surrounded by tangled arrows.",
    "The wolf laughing out loud holding his belly, tears of joy.",
    "The wolf worried, biting his nails, looking at his phone.",
    "The wolf sleeping peacefully in a hammock between two palm trees.",
    "The wolf meditating cross-legged on a mountain top at sunrise, calm.",
    "The wolf does a facepalm, shaking his head in disbelief.",
    "The wolf gives a big confident thumbs up, winking.",
    "The wolf shrugs with both palms up, uncertain smile.",
    "The wolf counting a thick stack of banknotes at a desk, focused.",
    "The wolf sweating nervously, loosening his tie, hot red background.",
    "The wolf standing proudly with hands on hips, cape fluttering behind him like a hero.",
    "The wolf surprised by a gift box popping open with sparkles.",
    "The wolf yawning, bored, chin on his hand at a desk.",
    "The wolf determined, rolling up his sleeves, ready to work.",
    "The wolf relieved, wiping his forehead and exhaling, sunny sky.",
]
T["office"] = [
    "The wolf works on a laptop at a modern glass desk, plants and big windows.",
    "The wolf teaches in front of a big whiteboard full of arrows and simple drawings.",
    "The wolf presents to a meeting room full of colleagues with a projector screen.",
    "The wolf on a phone call, standing by a big window overlooking the city.",
    "The wolf reads a big newspaper in a leather armchair with a coffee.",
    "The wolf writes notes in a notebook with a fountain pen, focused.",
    "The wolf takes a coffee break in a cozy office kitchen.",
    "The wolf looks out of a skyscraper window at the city at night, thoughtful.",
    "The wolf works late at night under a desk lamp, empty office around him.",
    "The wolf on a video call on a big monitor with several small faces.",
    "The wolf uses a big desk calculator, paper roll coming out.",
    "The wolf types very fast on a keyboard, motion lines, glowing screen.",
    "The wolf organizes colorful folders on a big shelf.",
    "The wolf at a standing desk with three monitors, morning light.",
    "The wolf studies in a quiet library between tall bookshelves.",
]
T["stocks"] = [
    "A busy stock exchange trading floor with traders and giant screens, the wolf in the middle.",
    "The wolf watches a long glowing ticker tape of prices running across a building facade.",
    "A big bronze bull statue on a city street, the wolf leaning on it confidently.",
    "A big bronze bear statue in a gloomy street, the wolf looking at it cautiously.",
    "A classic financial district street with tall old buildings and flags, the wolf walking with a briefcase.",
    "The wolf in front of a wall of trading screens all showing green rising charts, celebrating.",
    "The wolf in front of a wall of trading screens all showing red falling charts, worried.",
    "The wolf rings a big brass opening bell on a balcony above a trading floor.",
    "A shiny modern company headquarters tower with a glass facade, the wolf in front holding a stock certificate.",
    "The wolf visits a modern factory with robotic arms building products.",
    "The wolf at a shareholders meeting in a big auditorium raising his hand to ask a question.",
    "The wolf reads a thick annual report with charts and a highlighter.",
    "The wolf opens an envelope and gold coins pour out like a dividend payment.",
    "The wolf holds an elegant old stock certificate with a ribbon, vintage style.",
    "The wolf buys shares on a smartphone trading app, glowing green button.",
    "A huge green arrow chart climbing up a skyscraper, the wolf riding on top of it.",
    "A huge red arrow chart crashing down through the floor, the wolf holding on to it.",
    "A giant scoreboard of colorful tiles going up and down, the wolf watching with binoculars.",
    "A rocket shaped like a company building launching on its first day, confetti, the wolf watching.",
    "A crowd of panicking traders throwing papers in the air on a trading floor, the wolf calm in the middle.",
]
T["gold"] = [
    "The wolf stands next to a huge neat stack of shiny gold bars in a vault.",
    "A massive underground gold vault with rows of gold bars on shelves, the wolf walking with a flashlight.",
    "The wolf in a helmet with a headlamp inside a gold mine, gold veins in the rock.",
    "The wolf pans for gold in a river, a gold nugget sparkling in the pan.",
    "The wolf opens a treasure chest overflowing with gold coins and jewels.",
    "A jeweler weighs a small gold bar on a precise scale, the wolf watching closely.",
    "A golden chart arrow climbing over a pile of gold bars, the wolf smiling.",
    "Close-up of the wolf holding a heavy shiny gold bar in both paws, admiring it.",
    "A balance scale with a gold bar on one side and a tall pile of paper money on the other, the wolf comparing.",
    "The wolf holds a big gold nugget up to the light with tweezers, amazed.",
    "Molten gold being poured into a mold in a glowing refinery, the wolf in a protective apron.",
    "Gold dust sparkling in the wolf's open paws, magical light.",
]
T["metals"] = [
    "The wolf stands next to a neat stack of shiny silver bars.",
    "A pile of shiny silver coins on a velvet cloth, the wolf picking one up.",
    "Solar panels and electronics with glowing silver threads, the wolf explaining with a pointer.",
    "Big spools of copper wire and copper pipes in a warehouse, the wolf inspecting them.",
    "A huge open-pit copper mine with giant trucks, the wolf on a lookout platform.",
    "A battery factory with rows of glowing lithium cells, the wolf in a lab coat.",
    "The wolf charges an electric car at a modern charging station, city at night.",
    "The wolf holds a handful of strange colorful rare earth minerals in a mine.",
    "The wolf looks at a car's shiny catalytic converter in a garage, holding a platinum coin.",
    "A glowing steel mill with sparks and molten metal, the wolf in a hard hat.",
    "A mountain of aluminum cans at a recycling plant, the wolf on top.",
    "A metals trading board with different shiny metal bars displayed, the wolf choosing one.",
]
T["energy"] = [
    "A big oil rig in the middle of a stormy sea, the wolf on the helicopter pad.",
    "Rows of black oil barrels in a depot, the wolf counting them with a clipboard.",
    "The wolf at a gas station shocked by a huge glowing price sign without readable numbers.",
    "An oil refinery glowing at night with towers and flames, the wolf watching from a hill.",
    "A long oil pipeline crossing a desert at sunset, the wolf walking beside it.",
    "A huge solar farm in the sun, the wolf walking between the panels.",
    "Giant wind turbines on green hills, the wolf holding his hat in the wind.",
    "A nuclear power plant with cooling towers, the wolf in a safety helmet.",
    "A city at night full of lights connected by power lines, the wolf on a rooftop.",
    "The wolf at home wrapped in a blanket next to a radiator, looking at an energy bill.",
    "A control room of an electric grid with many screens, the wolf operating it.",
    "A giant oil tanker ship on the ocean, the wolf on the bow.",
]
T["realestate"] = [
    "The wolf proudly stands in front of a nice house with a garden, holding a sign without text.",
    "A modern apartment building with balconies, the wolf waving from one balcony.",
    "A real estate agent hands house keys to the wolf, both smiling.",
    "The wolf at a desk signing a thick pile of mortgage papers, worried face.",
    "A construction site with cranes and a building rising, the wolf in a hard hat.",
    "The wolf as a landlord receiving rent coins from a smiling tenant at a door.",
    "A small house on a rising green arrow, the wolf holding onto the roof.",
    "An empty office building with dark windows, the wolf looking at it from the street.",
    "The wolf looks at houses through a big shop window with glowing house pictures.",
    "A miniature model house on a desk next to a calculator and coins, the wolf planning.",
]
T["banking"] = [
    "A huge round bank vault door slowly opening, golden light inside, the wolf amazed.",
    "The wolf withdraws money from a modern ATM at night.",
    "The wolf drops a coin into a cute pink piggy bank on a table.",
    "Big stacks of banknotes on a table, the wolf sitting behind them.",
    "A glass jar slowly filling with coins on a windowsill, the wolf watching.",
    "The wolf juggles several credit cards, looking stressed.",
    "The wolf reads a long loan contract with a magnifying glass, frowning.",
    "A small tree with coins as leaves growing in a pot, the wolf watering it.",
    "A big printing press spitting out piles of paper money, the wolf shocked.",
    "A grand central bank building with columns and a giant clock, the wolf on the steps.",
    "A paper banknote shrinking in the wolf's hands while prices rise around him.",
    "The wolf opens an empty wallet, a moth flies out, funny.",
    "The wolf receives a paycheck envelope from his boss, happy.",
    "The wolf at a bank counter opening a savings account, a smiling banker.",
    "The wolf writes a monthly budget in a notebook with categories and coins.",
]
T["economy"] = [
    "A growing city skyline with cranes and new towers at sunrise, the wolf on a hill.",
    "Empty city streets with closed shops and grey sky, the wolf walking alone.",
    "A long line of people waiting outside an office building, the wolf in the line.",
    "The wolf pushes a shopping cart in a supermarket, shocked by tall price tags without numbers.",
    "Busy supermarket aisles full of products, the wolf choosing items carefully.",
    "Factory workers on an assembly line, the wolf as a manager with a clipboard.",
    "A huge port full of colorful shipping containers and cranes, the wolf on a container.",
    "A giant cargo ship sailing across the ocean loaded with containers.",
    "A world map with glowing lines of money flowing between continents, the wolf pointing.",
    "A government parliament building with flags, the wolf on the square in front.",
    "Politicians at podiums in a debate, the wolf in the audience taking notes.",
    "A stack of newspapers with dramatic front pages without readable text, the wolf reading one.",
    "A giant balloon labeled with a price tag inflating over a city, the wolf holding the string.",
    "A big control dial like an interest rate knob being turned by a giant hand, the wolf watching.",
    "Bars of a growing bar chart made of buildings, the wolf climbing to the top.",
]
T["crypto"] = [
    "Close-up of a shiny golden Bitcoin coin spinning in the air, sparkles.",
    "A glowing silver-blue Ethereum diamond floating above the wolf's open paw.",
    "A colorful pile of many different crypto coins on a table, the wolf sorting them.",
    "The wolf holds a phone with a glowing crypto wallet app, coins hovering above the screen.",
    "The wolf plugs a small hardware wallet into a laptop, careful.",
    "A chain of glowing transparent cubes floating through a digital space.",
    "A room full of crypto mining rigs with blinking lights and fans.",
    "The wolf uses a crypto exchange app with green and red buttons, focused.",
    "A crypto chart climbing to the moon, the wolf flying beside it with a jetpack.",
    "A crypto chart diving underwater, the wolf in a diving suit following it.",
    "A futuristic digital vault made of light protecting golden coins, the wolf as guard.",
    "Glowing keys and padlocks floating around a crypto coin.",
    "The wolf in a futuristic digital art gallery with glowing frames.",
    "Transparent glowing machines exchanging coins automatically, no humans, the wolf observing.",
    "A green coin with a dollar sign standing perfectly still on a pedestal while other coins bounce.",
    "A new glowing token being launched from a small rocket pad, a crowd watching.",
    "The wolf at a crowded crypto conference with a big stage and lights.",
    "The wolf uses a crypto ATM machine on a city street at night.",
    "The wolf pays at a shop by scanning a QR code with his phone.",
    "A laptop showing a glowing coin floating above the keyboard, the wolf typing.",
    "Gold coins raining from the sky over a neon city, the wolf with an umbrella upside down catching them.",
    "A rocket with a coin on top launching toward the moon, the wolf saluting.",
    "A network of glowing satellites connecting the globe with lines of light.",
    "A futuristic cyberpunk city with neon coin symbols on the buildings, the wolf on a rooftop.",
    "A golden Bitcoin coin resting next to gold bars in a vault, digital and physical gold together.",
]
T["security"] = [
    "A big glowing blue shield with a padlock protecting the wolf's phone.",
    "A shadowy hooded hacker in front of many screens in a dark room.",
    "A fishing hook coming out of an email envelope on a laptop screen, the wolf pulling back.",
    "A digital safe with a combination lock, the wolf entering a code.",
    "The wolf confirms a login with a code on his phone, a green check mark glowing.",
    "A red siren light flashing on the wolf's desk, alarm, danger.",
    "The wolf as a detective with a trench coat and magnifying glass examining a suspicious coin.",
    "A fake website on a laptop screen wrapped in yellow police tape, the wolf pointing at it.",
    "A suspicious envelope with a skull sticker in the wolf's mailbox.",
    "A wall of fire protecting a glowing server from small attacking bugs.",
    "A broken padlock lying on the floor, the wolf looking worried.",
    "The wolf opens a safe deposit box in a bank vault.",
    "The wolf scans his fingerprint on a glowing scanner to open a door.",
    "Security cameras watching a vault, the wolf giving a thumbs up to the camera.",
    "The wolf saves a backup to a glowing cloud above his laptop.",
]
T["psychology"] = [
    "A tiny angel and a tiny devil on the wolf's shoulders whispering to him.",
    "The wolf on a roller coaster going up and down, faces of joy and fear.",
    "A herd of sheep running in the same direction, the wolf walking the opposite way.",
    "A crowd of people running toward a shiny coin, the wolf watching from the side.",
    "The wolf looks at himself in a mirror, his reflection looks wiser.",
    "A glowing brain floating above the wolf's head with lightning sparks.",
    "The wolf playing chess, thinking about his next move.",
    "A balance scale with a flaming greed symbol on one side and a trembling fear ghost on the other.",
    "The wolf waits patiently on a bench at a bus stop, reading a book.",
    "A casino slot machine with flashing lights, the wolf walking away from it.",
    "The wolf holding a crumpled lottery ticket, disappointed.",
    "A fortune teller with a crystal ball, the wolf rolling his eyes.",
    "A big hourglass with sand running, the wolf sitting next to it calmly.",
    "The wolf lost in a hedge maze, looking for the exit.",
    "The wolf standing at a crossroads with many signposts pointing in different directions.",
]
T["learning"] = [
    "The wolf as a teacher in a classroom, students raising their hands.",
    "A blackboard covered with simple math and coin drawings, the wolf with chalk.",
    "A tall stack of books with the wolf reading on top of it.",
    "The wolf in a graduation cap and gown, tossing the cap in the air.",
    "The wolf looks through a big magnifying glass at a tiny coin with details.",
    "A long checklist on a clipboard with green ticks, the wolf ticking the last box.",
    "A big glowing lightbulb above the wolf's head, eureka moment.",
    "The wolf assembles big puzzle pieces into a complete picture of a coin.",
    "The wolf reads an old treasure map with a compass on a wooden table.",
    "The wolf climbs a tall ladder toward a shining star.",
    "The wolf draws a step-by-step plan on a big notebook page.",
    "A wooden signpost with many arrows at a forest crossroads, the wolf reading it.",
]
T["time"] = [
    "Calendar pages flying away in the wind, the wolf watching them.",
    "A giant clock tower, the wolf checking his golden watch below it.",
    "A small seed growing into a big tree full of gold coins over time, time-lapse style.",
    "An old grey-bearded wolf in a rocking chair smiling, counting a big pile of coins, cozy home.",
    "A snowball made of coins rolling down a hill, growing bigger.",
    "A very long staircase reaching above the clouds, the wolf climbing step by step.",
    "A long straight road going to the horizon at sunrise, the wolf walking on it with a backpack.",
    "The wolf planting small seeds in a garden with a watering can.",
    "The wolf harvesting golden fruits from a tall tree into a basket.",
    "A beautiful sunrise over the sea, the wolf with a coffee on a balcony, new day.",
]
T["world"] = [
    "A big glowing globe spinning, the wolf pointing at different countries.",
    "The wolf looks out of an airplane window at clouds, traveling.",
    "The wolf in Tokyo at night with neon signs and crowds.",
    "The wolf in London near a red double-decker bus and a big clock tower.",
    "The wolf in New York with yellow taxis and tall skyscrapers.",
    "The wolf in Frankfurt with modern bank towers by the river.",
    "The wolf at a currency exchange counter holding different banknotes.",
    "The wolf shows his passport at an airport gate.",
    "A colorful world map on a wall with pins and strings, the wolf studying it.",
    "The wolf in Dubai with very tall futuristic towers in the desert sun.",
]
T["tech"] = [
    "A friendly humanoid robot shaking hands with the wolf in a futuristic lab.",
    "A huge data center with endless rows of blinking servers, the wolf walking through.",
    "A clean room chip factory with workers in white suits, the wolf in a white suit too.",
    "The wolf unboxes a brand new smartphone, excited.",
    "A factory line building electric cars with robotic arms, the wolf supervising.",
    "Colorful social media style icons floating in a cloud above a city.",
    "Mountains of delivery boxes in a giant warehouse, the wolf on a forklift.",
    "The wolf on a sofa watching a streaming show on a big TV with popcorn.",
    "Warehouse robots moving shelves automatically, the wolf amazed.",
    "Glowing data clouds connected to many devices, the wolf holding a tablet.",
    "A shiny silicon wafer with rainbow reflections held by the wolf with gloves.",
    "The wolf codes on two screens full of colorful code, hacker style but friendly.",
]
T["misc"] = [
    "The wolf relaxes on a luxury yacht deck with sunglasses, blue sea.",
    "The wolf works on a laptop on a sunny beach under an umbrella.",
    "The wolf drives a shiny red sports car on a coastal road.",
    "The wolf stands on a mountain peak with a flag, victorious.",
    "The wolf walks in the rain with an umbrella through a neon city.",
    "The wolf in a winter coat in a snowy city, holding a warm drink.",
    "The wolf fishes calmly from a small boat on a quiet lake at dawn.",
    "The wolf gardens happily, taking care of plants.",
    "The wolf looks out of a train window at a passing landscape.",
    "The wolf waits at an airport with a suitcase, looking at departure screens without readable text.",
    "The wolf watches the sunset from a rooftop, the city lights turning on.",
    "The wolf in a glass elevator going up the outside of a skyscraper, happy.",
    "The wolf in a glass elevator going down fast, scared.",
    "The wolf walks across a long suspension bridge at sunrise.",
    "The wolf builds a house of bricks, strong and patient.",
]
T["cta"] = [
    "The wolf points at the viewer from a luxury penthouse with a city view at night.",
    "The wolf points at the viewer while sitting on a pile of gold coins.",
    "The wolf points at the viewer in front of a giant green rising chart.",
    "The wolf points at the viewer from a sports car window, sunglasses on.",
    "The wolf points at the viewer on a stage with spotlights and confetti.",
    "The wolf points at the viewer from a classroom in front of a blackboard.",
    "The wolf points at the viewer standing in a bank vault full of gold.",
    "The wolf points at the viewer with a smartphone in his other hand, neon city.",
    "The wolf points at the viewer from a private jet seat, clouds outside the window.",
    "The wolf points at the viewer in a cozy library with a book under his arm.",
    "The wolf points at the viewer from the top of a mountain at sunrise.",
    "The wolf points at the viewer on a busy trading floor, screens behind him.",
    "The wolf points at the viewer from a beach chair with a laptop.",
    "The wolf points at the viewer in front of a bitcoin-shaped neon sign.",
    "The wolf points at the viewer holding a gold bar in his other paw.",
    "The wolf points at the viewer under an umbrella in a rainy neon street.",
    "The wolf points at the viewer from behind a big desk in a luxury office.",
    "The wolf points at the viewer with a coffee cup in his other paw, morning cafe.",
    "The wolf points at the viewer in front of a futuristic city skyline at dusk.",
    "The wolf points at the viewer from a podcast studio with a microphone.",
    "The wolf points at the viewer on a rooftop with fireworks in the sky.",
    "The wolf points at the viewer next to a huge golden trophy.",
    "The wolf points at the viewer from a train window, landscape passing.",
    "The wolf points at the viewer in a snowy street holding a warm drink.",
    "The wolf points at the viewer while walking on a stock exchange street with flags.",
]


def all_prompts():
    out = {}
    k = 0
    for theme, items in T.items():
        for scene in items:
            k += 1
            out[f"L{k:03d}"] = {"theme": theme, "p": scene}
    return out


if __name__ == "__main__":
    lib = all_prompts()
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "library_prompts.json")
    json.dump(lib, open(path, "w"), indent=1, ensure_ascii=False)
    from collections import Counter
    print(len(lib), dict(Counter(v["theme"] for v in lib.values())))
